module.exports = {
  four00: {
    error: 'BAD_REQUEST',
    errorMessage: 'The request failed because it contained an invalid value.',
  },
  four01: {
    error: 'UNAUTHORIZED',
    errorMessage: 'The user is not authorized to make the request.',
  },
  four04: {
    error: 'NOT_FOUND',
    errorMessage: 'The requested operation failed because a resource associated with the request could not be found.',
  },
  five00: {
    error: 'INTERNAL_SERVER_ERROR',
    errorMessage: 'The request failed due to an internal error.',
  },
  five03: {
    error: 'SERVICE_UNAVAILABLE',
    errorMessage: 'The request failed due to an internal error.',
  },
};
